name: WEATHER APP CI

on:
  push:
    branches:
      - main
      - feature/Variables
  pull_request:
    branches:
      - develop

env:
  App_name: "Wheather-App"
  Node_Version: "20"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TipoEjecucion: "Validacion de variables"

    steps:
      - name: Mostrar Variables Todas
        run: |
          echo "=== REVISANDO CONFIGURACIÓN ==="
          echo "Nombre de la Aplicación: ${{ env.App_name }}"
          echo "Versión de Node planificada: ${{ env.Node_Version }}"
          echo "Tipo de Ejecución actual: ${{ env.TipoEjecucion }}"

      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.Node_Version }}
          cache: "npm"

      - name: Instalar Dependencias
        run: npm ci

      - name: Validar Estilo de Código (Lint)
        run: npm run lint

      - name: Construir Proyecto (Build Next.js)
        run: npm run build
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
